---
name: fleet-adapter
services:
  adapter:
    image: fleet-adapter:${ROS_DISTRO}-${VERSION}
    environment:
      FLEET_CONFIG_FILE: /home/robot/config/config_robotnik_fleet.yaml
      GRAPH_CONFIG_FILE: /home/robot/graph/0.yaml
